trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '10.x'

- task: DotNetCoreCLI@2
  displayName: 'Compilar'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publicar artefacto'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'

- task: AzureWebApp@1
  displayName: 'Desplegar en Azure'
  inputs:
    azureSubscription: 'Azure for Students (5973f7f4-d280-4fc6-b4da-a0d97d3b7e2e)'
    appType: 'webAppWindows'
    appName: 'inventario-api'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'