trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '10.x'
  azureServiceConnection: 'Azure for Students (5973f7f4-d280-4fc6-b4da-a0d97d3b7e2e)' 
  webAppName: 'inventario-api' 

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Compilar'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publicar artefacto'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefacto'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: AzureWebApp@1
  displayName: 'Desplegar en Azure'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appType: 'webAppWindows'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
